/**
 * questions.js
 * 
 * Each question displays in Chinese (Traditional) to the user.
 * The `field` key maps to the exact English column name the model expects.
 * The `value` in each option is the integer the model receives.
 * 
 * This maintains complete separation between UI language and model input.
 */

export const questions = [
  // ── SECTION 1: Basic Information ─────────────────────────────────────────
  {
    id: 1,
    section: '基本資料',
    field: 'Age',
    type: 'slider',
    zh: '請問您的年齡是？',
    icon: '🎂',
    min: 40, max: 100, step: 1, defaultValue: 70,
    unit: '歲',
    description: '年齡是評估認知健康的重要參考指標。',
  },
  {
    id: 2,
    section: '基本資料',
    field: 'Gender',
    type: 'choice',
    zh: '請問您的性別是？',
    icon: '👤',
    options: [
      { label: '男性', icon: '👨', value: 0 },
      { label: '女性', icon: '👩', value: 1 },
    ],
  },
  {
    id: 3,
    section: '基本資料',
    field: 'Ethnicity',
    type: 'choice',
    zh: '請問您的族裔背景是？',
    icon: '🌏',
    options: [
      { label: '白人／歐裔', icon: '🌍', value: 0 },
      { label: '非裔', icon: '🌍', value: 1 },
      { label: '亞裔', icon: '🌏', value: 2 },
      { label: '其他', icon: '🌎', value: 3 },
    ],
  },
  {
    id: 4,
    section: '基本資料',
    field: 'EducationLevel',
    type: 'choice',
    zh: '您目前最高學歷為何？',
    icon: '🎓',
    options: [
      { label: '無正式學歷', icon: '📝', value: 0 },
      { label: '高中 / 職', icon: '🏫', value: 1 },
      { label: '大學 / 專科', icon: '🎓', value: 2 },
      { label: '研究所以上', icon: '📚', value: 3 },
    ],
  },
  {
    id: 5,
    section: '基本資料',
    field: 'BMI',
    type: 'slider',
    zh: '請問您的身體質量指數 (BMI) 大約是？',
    icon: '⚖️',
    min: 15, max: 45, step: 0.5, defaultValue: 25,
    unit: '',
    description: 'BMI = 體重(kg) ÷ 身高(m)²。一般健康範圍為 18.5–24.9。',
  },

  // ── SECTION 2: Lifestyle ───────────────────────────────────────────────
  {
    id: 6,
    section: '生活習慣',
    field: 'Smoking',
    type: 'choice',
    zh: '您目前有吸菸習慣嗎？',
    icon: '🚭',
    options: [
      { label: '從未或已戒菸', icon: '✅', value: 0 },
      { label: '目前仍在吸菸', icon: '🚬', value: 1 },
    ],
  },
  {
    id: 7,
    section: '生活習慣',
    field: 'AlcoholConsumption',
    type: 'slider',
    zh: '您每週飲酒的頻率大約是？',
    icon: '🍷',
    min: 0, max: 20, step: 0.5, defaultValue: 5,
    unit: '單位/週',
    description: '1 單位 ≈ 一罐啤酒 / 一杯紅酒 / 一小杯烈酒。',
  },
  {
    id: 8,
    section: '生活習慣',
    field: 'PhysicalActivity',
    type: 'slider',
    zh: '您每週規律運動的程度如何？',
    icon: '🏃',
    min: 0, max: 10, step: 0.5, defaultValue: 5,
    unit: '分（0＝完全不運動，10＝非常規律）',
    description: '每週至少 150 分鐘中等強度運動有助於維持大腦健康。',
  },
  {
    id: 9,
    section: '生活習慣',
    field: 'DietQuality',
    type: 'slider',
    zh: '您的日常飲食品質如何？',
    icon: '🥗',
    min: 0, max: 10, step: 0.5, defaultValue: 5,
    unit: '分（0＝非常不健康，10＝非常均衡）',
    description: '地中海飲食（蔬果、橄欖油、堅果、魚）有助於認知健康。',
  },
  {
    id: 10,
    section: '生活習慣',
    field: 'SleepQuality',
    type: 'slider',
    zh: '您最近的睡眠品質如何？',
    icon: '😴',
    min: 0, max: 10, step: 0.5, defaultValue: 7,
    unit: '分（0＝非常差，10＝非常好）',
    description: '充足高品質的睡眠有助於大腦清除代謝廢物。',
  },

  // ── SECTION 3: Medical History ────────────────────────────────────────
  {
    id: 11,
    section: '健康病史',
    field: 'FamilyHistoryAlzheimers',
    type: 'choice',
    zh: '您的直系家屬（父母、兄弟姊妹）中，有人被診斷為阿茲海默症嗎？',
    icon: '👨‍👩‍👧',
    options: [
      { label: '沒有', icon: '✅', value: 0 },
      { label: '有', icon: '⚠️', value: 1 },
    ],
  },
  {
    id: 12,
    section: '健康病史',
    field: 'CardiovascularDisease',
    type: 'choice',
    zh: '您是否曾被診斷為心臟病或心血管疾病？',
    icon: '❤️',
    options: [
      { label: '沒有', icon: '✅', value: 0 },
      { label: '有', icon: '⚠️', value: 1 },
    ],
  },
  {
    id: 13,
    section: '健康病史',
    field: 'Diabetes',
    type: 'choice',
    zh: '您是否有糖尿病？',
    icon: '💉',
    options: [
      { label: '沒有', icon: '✅', value: 0 },
      { label: '有', icon: '⚠️', value: 1 },
    ],
  },
  {
    id: 14,
    section: '健康病史',
    field: 'Depression',
    type: 'choice',
    zh: '您是否曾被診斷或治療過憂鬱症？',
    icon: '🧠',
    options: [
      { label: '沒有', icon: '✅', value: 0 },
      { label: '有', icon: '⚠️', value: 1 },
    ],
  },
  {
    id: 15,
    section: '健康病史',
    field: 'HeadInjury',
    type: 'choice',
    zh: '您曾有過嚴重的頭部受傷（如腦震盪）嗎？',
    icon: '🤕',
    options: [
      { label: '沒有', icon: '✅', value: 0 },
      { label: '有', icon: '⚠️', value: 1 },
    ],
  },
  {
    id: 16,
    section: '健康病史',
    field: 'Hypertension',
    type: 'choice',
    zh: '您是否有高血壓？',
    icon: '💊',
    options: [
      { label: '沒有', icon: '✅', value: 0 },
      { label: '有', icon: '⚠️', value: 1 },
    ],
  },

  // ── SECTION 4: Clinical Measurements ─────────────────────────────────
  {
    id: 17,
    section: '臨床數值',
    field: 'SystolicBP',
    type: 'slider',
    zh: '您最近量測的收縮壓（高壓）大約是？',
    icon: '🩺',
    min: 80, max: 220, step: 1, defaultValue: 120,
    unit: 'mmHg',
    description: '正常範圍：90–120 mmHg。若不確定請填寫 120。',
  },
  {
    id: 18,
    section: '臨床數值',
    field: 'DiastolicBP',
    type: 'slider',
    zh: '您最近量測的舒張壓（低壓）大約是？',
    icon: '🩺',
    min: 40, max: 140, step: 1, defaultValue: 80,
    unit: 'mmHg',
    description: '正常範圍：60–80 mmHg。若不確定請填寫 80。',
  },
  {
    id: 19,
    section: '臨床數值',
    field: 'CholesterolTotal',
    type: 'slider',
    zh: '您最近的總膽固醇數值大約是？',
    icon: '🔬',
    min: 100, max: 400, step: 1, defaultValue: 200,
    unit: 'mg/dL',
    description: '建議值低於 200 mg/dL。若不確定請填寫 200。',
  },
  {
    id: 20,
    section: '臨床數值',
    field: 'CholesterolLDL',
    type: 'slider',
    zh: '您的 LDL（壞膽固醇）數值大約是？',
    icon: '🔬',
    min: 20, max: 300, step: 1, defaultValue: 100,
    unit: 'mg/dL',
    description: '建議值低於 100 mg/dL。若不確定請填寫 100。',
  },
  {
    id: 21,
    section: '臨床數值',
    field: 'CholesterolHDL',
    type: 'slider',
    zh: '您的 HDL（好膽固醇）數值大約是？',
    icon: '🔬',
    min: 10, max: 150, step: 1, defaultValue: 55,
    unit: 'mg/dL',
    description: '建議值高於 40 mg/dL。若不確定請填寫 55。',
  },
  {
    id: 22,
    section: '臨床數值',
    field: 'CholesterolTriglycerides',
    type: 'slider',
    zh: '您的三酸甘油酯數值大約是？',
    icon: '🔬',
    min: 30, max: 500, step: 5, defaultValue: 150,
    unit: 'mg/dL',
    description: '建議值低於 150 mg/dL。若不確定請填寫 150。',
  },

  // ── SECTION 5: Cognitive Assessment ──────────────────────────────────
  {
    id: 23,
    section: '認知評估',
    field: 'MMSE',
    type: 'slider',
    zh: '如果您曾做過認知測驗（MMSE），分數大約是多少？',
    icon: '🧩',
    min: 0, max: 30, step: 1, defaultValue: 24,
    unit: '分（滿分30分）',
    description: '24分以上為正常；若未曾測驗，可保留預設值 24。',
  },
  {
    id: 24,
    section: '認知評估',
    field: 'FunctionalAssessment',
    type: 'slider',
    zh: '您認為自己整體的日常功能表現如何？',
    icon: '⚡',
    min: 0, max: 10, step: 0.5, defaultValue: 7,
    unit: '分（0＝嚴重受限，10＝完全正常）',
    description: '包括工作、社交、日常安排的處理能力。',
  },
  {
    id: 25,
    section: '認知評估',
    field: 'ADL',
    type: 'slider',
    zh: '您在日常生活活動（如穿衣、洗澡、煮飯）上的獨立程度如何？',
    icon: '🏠',
    min: 0, max: 10, step: 0.5, defaultValue: 8,
    unit: '分（0＝完全需要協助，10＝完全獨立）',
    description: '日常生活活動能力（ADL）是評估失能程度的重要指標。',
  },

  // ── SECTION 6: Symptoms ───────────────────────────────────────────────
  {
    id: 26,
    section: '認知症狀',
    field: 'MemoryComplaints',
    type: 'choice',
    zh: '您最近是否常覺得記性變差、容易忘事？',
    icon: '💭',
    options: [
      { label: '幾乎不會', icon: '🌿', value: 0 },
      { label: '是，有這種感覺', icon: '⚠️', value: 1 },
    ],
  },
  {
    id: 27,
    section: '認知症狀',
    field: 'BehavioralProblems',
    type: 'choice',
    zh: '您或家人是否注意到您最近有不尋常的行為或情緒變化？',
    icon: '🔄',
    options: [
      { label: '沒有', icon: '✅', value: 0 },
      { label: '有', icon: '⚠️', value: 1 },
    ],
  },
  {
    id: 28,
    section: '認知症狀',
    field: 'Confusion',
    type: 'choice',
    zh: '您最近是否有時感到思緒混亂，無法清楚思考？',
    icon: '🌀',
    options: [
      { label: '沒有', icon: '✅', value: 0 },
      { label: '有', icon: '⚠️', value: 1 },
    ],
  },
  {
    id: 29,
    section: '認知症狀',
    field: 'Disorientation',
    type: 'choice',
    zh: '您最近是否偶爾對時間、地點或人物感到困惑？',
    icon: '🧭',
    options: [
      { label: '沒有', icon: '✅', value: 0 },
      { label: '有', icon: '⚠️', value: 1 },
    ],
  },
  {
    id: 30,
    section: '認知症狀',
    field: 'PersonalityChanges',
    type: 'choice',
    zh: '家人或朋友是否提及您的個性近期有明顯改變？',
    icon: '🎭',
    options: [
      { label: '沒有', icon: '✅', value: 0 },
      { label: '有', icon: '⚠️', value: 1 },
    ],
  },
  {
    id: 31,
    section: '認知症狀',
    field: 'DifficultyCompletingTasks',
    type: 'choice',
    zh: '您最近是否對以前熟悉的工作或任務感到困難？',
    icon: '📋',
    options: [
      { label: '沒有', icon: '✅', value: 0 },
      { label: '有', icon: '⚠️', value: 1 },
    ],
  },
  {
    id: 32,
    section: '認知症狀',
    field: 'Forgetfulness',
    type: 'choice',
    zh: '您最近是否常忘記剛發生的事情，例如剛說過的話或剛做的事？',
    icon: '🔔',
    options: [
      { label: '幾乎不會', icon: '🌿', value: 0 },
      { label: '是，常常發生', icon: '⚠️', value: 1 },
    ],
  },
]

export const sections = [...new Set(questions.map(q => q.section))]

export const defaultAnswers = {
  Age: 70,
  Gender: 0,
  Ethnicity: 0,
  EducationLevel: 1,
  BMI: 25,
  Smoking: 0,
  AlcoholConsumption: 5,
  PhysicalActivity: 5,
  DietQuality: 5,
  SleepQuality: 7,
  FamilyHistoryAlzheimers: 0,
  CardiovascularDisease: 0,
  Diabetes: 0,
  Depression: 0,
  HeadInjury: 0,
  Hypertension: 0,
  SystolicBP: 120,
  DiastolicBP: 80,
  CholesterolTotal: 200,
  CholesterolLDL: 100,
  CholesterolHDL: 55,
  CholesterolTriglycerides: 150,
  MMSE: 24,
  FunctionalAssessment: 7,
  ADL: 8,
  MemoryComplaints: 0,
  BehavioralProblems: 0,
  Confusion: 0,
  Disorientation: 0,
  PersonalityChanges: 0,
  DifficultyCompletingTasks: 0,
  Forgetfulness: 0,
}
